<?php

/**
 * @file loadtermnames.module
 */

/**
 * Implements hook_entity_load().
 */
function loadtermnames_entity_load($entities, $type) {
  $tids = array();

  $term_fields = _loadtermnames_get_term_fields();

  foreach ($entities as $entity) {
    foreach ($term_fields as $term_field_name => $term_field_info) {
      $items = field_get_items($type, $entity, $term_field_name);
      if ($items) {
        foreach ($items as $item) {
          $tids[$item['tid']] = null;
        }
      }
    }
  }

  if (count($tids) < 1) {
    return;
  }

  $query = db_query('SELECT tid,name FROM taxonomy_term_data WHERE tid IN (:tids)', array(':tids' => array_keys($tids)));
  $tids = $query->fetchAllAssoc('tid');

  foreach ($entities as $entity) {
    foreach ($term_fields as $term_field_name => $term_field_info) {
      // discover langue the easy way or the hard way
      if (property_exists($entity, 'language')) {
        $lang = $entity->language;
      } else {
        $lang = field_language($type, $entity, $term_field_name);
      }

      $items = field_get_items($type, $entity, $term_field_name);

      if ($items) {
        $items_with_names = array();

        foreach ($items as $item) {
          $items_with_names[$item['tid']] = array(
            'tid' => $item['tid'],
            'name' => $tids[$item['tid']]->name,
          );
        }

        $entity->{$term_field_name}[$lang] = $items_with_names;
      }
    }
  }
}

function _loadtermnames_get_term_fields() {
  $term_fields = &drupal_static(__FUNCTION__);

  if (!isset($term_fields)) {
    $term_fields = array_filter(field_info_field_map(), function($field) {
      return $field["type"] == "taxonomy_term_reference";
    });
  }

  return $term_fields;
}

